<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon />
    <AssemblyName>Kairix.QuickAVSync</AssemblyName>
    <RootNamespace>Kairix.QuickAVSync</RootNamespace>
    <VersionPrefix>0.1.0</VersionPrefix>
    <VersionSuffix>alpha</VersionSuffix>
    <Product>Kairix Quick A/V Sync</Product>
    <Description>Windows audio/video synchronization measurement utility</Description>
    <Authors>Dubcodes</Authors>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Kairix.QuickAVSync.Core\Kairix.QuickAVSync.Core.csproj" />
    <ProjectReference Include="..\Kairix.QuickAVSync.Windows\Kairix.QuickAVSync.Windows.csproj" />
  </ItemGroup>

</Project>
